#!/usr/bin/env python3

# import rospy
import rclpy
from vgc10_msgs.msg import OnRobotVGInput


def printStatus(status):
    """Prints the status string generated by the statusInterpreter function."""

    # rospy.loginfo(statusInterpreter(status))


def OnRobotVGStatusListener():
    """Initializes the node and subscribe to the OnRobotVGInput topic."""

    # rospy.init_node('OnRobotVGStatusListener', log_level=rospy.DEBUG)
    # rospy.Subscriber("OnRobotVGInput", OnRobotVGInput, printStatus)
    # rospy.spin()
    rclpy.init()
    node = rclpy.create_node('OnRobotVGStatusListener')
    subscription = node.create_subscription(OnRobotVGInput, 'OnRobotVGInput', printStatus)
    rclpy.spin(node)

def statusInterpreter(status):
    """Generates a string according to the current value
       of the status variables.
    """

    output = '\n-----\nOnRobot VG status interpreter\n-----\n'

    # gVCA
    output += 'gVCA = ' + str(status.gVCA) + ': '
    output += 'Current vacuum value on Channel A: ' + str(status.gVCA) + '\n'

    # gVCB
    output += 'gVCB = ' + str(status.gVCB) + ': '
    output += 'Current vacuum value on Channel B: ' + str(status.gVCB) + '\n'

    return output


if __name__ == '__main__':
    OnRobotVGStatusListener()